// GENERATED by scripts/derive-transparent-families.mjs. Do not edit by hand.
import type { FamilyKey } from './districtIdentity'

export interface SilhouetteBounds {
  x0: number
  y0: number
  x1: number
  y1: number
}

/** Friend silhouette bounds per family asset, in the assets' 512×512 viewBox. */
export const FAMILY_ART_VIEWBOX = 512
export const FAMILY_ART_METRICS: Record<FamilyKey, Record<1 | 2, SilhouetteBounds>> = {
  asymmetry: {
    1: { x0: 112, y0: 48, x1: 400, y1: 464 },
    2: { x0: 96, y0: 48, x1: 416, y1: 464 },
  },
  cellular: {
    1: { x0: 96, y0: 32, x1: 416, y1: 480 },
    2: { x0: 160, y0: 80, x1: 352, y1: 432 },
  },
  colossus: {
    1: { x0: 0, y0: 64, x1: 512, y1: 448 },
    2: { x0: 0, y0: 48, x1: 512, y1: 464 },
  },
  family: {
    1: { x0: 96, y0: 32, x1: 416, y1: 480 },
    2: { x0: 96, y0: 32, x1: 416, y1: 480 },
  },
  hollow: {
    1: { x0: 96, y0: 32, x1: 416, y1: 480 },
    2: { x0: 96, y0: 32, x1: 416, y1: 480 },
  },
  hoverer: {
    1: { x0: 128, y0: 32, x1: 384, y1: 480 },
    2: { x0: 96, y0: 32, x1: 416, y1: 480 },
  },
  mask: {
    1: { x0: 32, y0: 32, x1: 480, y1: 480 },
    2: { x0: 64, y0: 32, x1: 448, y1: 480 },
  },
  skeleton: {
    1: { x0: 96, y0: 32, x1: 416, y1: 480 },
    2: { x0: 96, y0: 32, x1: 416, y1: 480 },
  },
  sparkling: {
    1: { x0: 32, y0: 32, x1: 480, y1: 480 },
    2: { x0: 32, y0: 32, x1: 480, y1: 480 },
  },
}
